[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs" 

[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "npm run build" 